name: Zola on GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: write

jobs:
  build_test:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout de la PR
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Test de compilación (Sin despliegue)
        uses: shalzz/zola-deploy-action@v0.21.0
        env:
          BUILD_ONLY: true
          BUILD_FLAGS: --drafts

  build_and_deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout de main
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Compilar y Desplegar a producción
        uses: shalzz/zola-deploy-action@v0.21.0
        env:
          PAGES_BRANCH: gh-pages
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
