name: Despliegue de Zola

on:
  push:
    branches:
      - main
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código fuente
        uses: actions/checkout@v4
        with:
          submodules: true 

      - name: Compilar y Desplegar Zola
        uses: shalzz/zola-deploy-action@v0.19.0
        env:
          PAGES_BRANCH: gh-pages
          BUILD_DIR: public
          # ZOLA_VERSION: 0.16.1 # Descomenta esta línea si falla por el error de get_section
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
